### ISSUE TITLE
这句报错，还有noisy是指的clean和noise合成之后音频吧

### ISSUE THREAD

**Issue by wbjnpu** [BYRTIMO/END-TO-END-SPEECH-ENHANCEMENT-BASED-ON-DISCRETE-COSINE-TRANSFORM#1]
grads = opt.compute_gradients(loss_fn, var_list=[var for var in tf.trainable_variables()])

**Comment by BYRTIMO** [comment]
对的，错误我看下

**Comment by wbjnpu** [comment]
> 对的，错误我看下

Traceback (most recent call last):
  File "train.py", line 122, in <module>
    train(cfg)
  File "train.py", line 58, in train
    grads = opt.compute_gradients(loss_fn, var_list=[var for var in tf.trainable_variables()])
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 519, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 630, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 814, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 408, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 814, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 328, in _UnsortedSegmentSumGrad
    return _GatherDropNegatives(grad, op.inputs[1])[0], None, None
  File "/home/npu/anaconda3/envs/wbj/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 296, in _GatherDropNegatives
    for _ in range(gathered.shape.ndims - is_positive.shape.ndims):
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
这个，哪里的数据类型不一样吧

**Comment by BYRTIMO** [comment]
嗯嗯，应该是最后一句“gathered.shape.ndims - is_positive.shape.ndims”中减号两边数据类型不同，参照“https://stackoverflow.com/questions/47100024/unsupported-operand-types-for-nonetype-and-int”，你可以看下。

**Comment by wbjnpu** [comment]
> 嗯嗯，应该是最后一句“gathered.shape.ndims - is_positive.shape.ndims”中减号两边数据类型不同，参照“[https://stackoverflow.com/questions/47100024/unsupported-operand-types-for-nonetype-and-int”，你可以看下。](https://stackoverflow.com/questions/47100024/unsupported-operand-types-for-nonetype-and-int%E2%80%9D%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E7%9C%8B%E4%B8%8B%E3%80%82)

这修改tensorflow源码么

**Comment by BYRTIMO** [comment]
我没有修改过，我的tensorflow版本为1.13

**Comment by wbjnpu** [comment]
请问有预训练模型提供一下么

**Comment by Huer-H** [comment]
你好，问下这个noisy路径下的文件和clean路径下的文件是一一对应的吗？
比如：
mix/a.wav    clean/a.wav？
mix和clean路径下的数量是一致的吗？

**Comment by Huer-H** [comment]
是不是按照徐勇老师那个代码合成的noisy呢？
多个mix对应一个clean？
